FROM python:3.10

WORKDIR /src

COPY pyproject.toml poetry.lock /src/

RUN python -m pip install poetry

RUN poetry config virtualenvs.create false && poetry install

COPY ./hometasks ./hometasks

EXPOSE 8081

CMD ["uvicorn", "hometasks.contacts_api.main:app", "--port", "8081", "--host", "0.0.0.0"]
